export enum ConstantsI {
    PLACES_REQUEST = 'PLACES_REQUEST',
    PLACES_SUCCESS = 'PLACES_SUCCESS',
    PLACES_ALLPLACES = 'PLACES_ALLDATA',
    PLACES_ADD_NEW_PACE = 'PLACES_ADD_NEW_PACE',
    PLACES_ERROR = 'PLACES_ERROR'
}

