export enum ConstantsI {
    LOGIN_REQUEST = 'LOGIN_REQUEST',
    LOGIN_SUCCESS = 'LOGIN_SUCCESS',
    LOGIN_ERROR = 'LOGIN_ERROR',
    CURRENT_UID = 'CURRENT_UID',
    PERSONAL_DATA = "PERSONAL_DATA"
}

